### ISSUE TITLE
Port over API classes from the MATLAB code to Python

### ISSUE THREAD

**Issue by DrPaulSharp** [RascalSoftware/python-RAT#1]
We need to port over the following classes from the MATLAB version of RAT to python:

- [x] #7 -- Added in #10
- [x] `eventManager` -- Added in #21
- [x] `backgroundsClass` -- Added in #6 
- [x] `baseContrasts` -- Added in #6 
- [x] `contrastsClass` -- Added in #6 
- [x] `customFileClass` -- Added in #6 
- [x] `dataClass` -- Added in #6 
- [x] `domainContrastsClass` -- Added in #6 
- [x] `domainsClass` -- Added in #14
- [x] `layersClass` -- Added in #6 
- [x] ~~`multiTypeTable`~~ -- Not required
- [x] `parametersClass` -- Added in #6 
- [x] `projectClass` -- Added in #6 
- [x] `resolutionsClass` -- Added in #6 
- [x] ~~`tableUtilities`~~ -- Not required, broad equivalent is the ClassList added in #4 

We also need the following utility functions:

- [x] `duplicateName` -- Added in ClassList in #4
- [x] `indexOutOfRange` -- Covered by python builtins
- [x] ~~`invalidNumberOfInputs`~~ -- Not required
- [x] `invalidOption` -- Covered by pydantic #6 
- [x] `invalidProperty` -- Covered by #14 
- [x] `invalidType` -- Covered by pydantic #6
- [x] `invalidValue` -- Covered by pydantic #6 & #10
- [x] `nameNotRecognised` -- Covered by ClassList #4 
- [x] ~~`unrecognisedR1Problem`~~ -- not necessary, use regular python error types
- [x] `projectClasstoR1`  -- added in #55
- [x] `r1toProjectClass` -- added in #55
- [x] `bayesShadedPlot` -- added in #52 
- [x] `cornerPlot` -- added in #52 
- [x] `histp` -- added in #52 
- [x] `mcmcplot` -- added in #52 
- [x] `plotBayes` -- added in #52 
- [x] ~~`plotBayesCorrFig`~~ -- removed from matlab RAT
- [x] `plotRefSLD` -- Added in #24 
- [x] `plotRefSLDHelper` -- Added in #24 
- [x] ~~`shade`~~ -- not required as already in matplotlib
- [x] ~~`copyProperties`~~ -- Not required
- [x] ~~`customEnum`~~ -- Not required
- [x] ~~`isText`~~ -- Not required
- [x] ~~`mockFunction`~~ -- Not required
- [x] `validateNumber` -- Covered by pydantic #6  
- [x] `validateOption` -- Covered by pydantic #6  

We will need to port over all the examples -- most done in #36

**Comment by alexhroom** [comment]
[`corner`: a `matplotlib` extension for corner plots](https://corner.readthedocs.io/en/latest/)
